  module "rds" {
    source                 = "terraform-aws-modules/rds/aws"
    version                = "6.6.0"
    identifier             = "appdb"
    engine                 = "mysql"
    engine_version         = "8.4.7"
    major_engine_version   = "8.4"
    family                 = "mysql8.4"
    instance_class         = "db.t3.micro"
    create_db_subnet_group = true
    subnet_ids             = module.vpc["private_vpc"].private_subnets
    allocated_storage      = 20
    db_name                = var.db_name
    username               = var.db_username
    manage_master_user_password = false
    password               = var.db_password
    publicly_accessible    = false
    skip_final_snapshot    = true
    availability_zone      = var.azs[0]
    vpc_security_group_ids = [module.security-group.security_group_id]
    depends_on             = [module.security-group]
  }